{% set name = "perl-uri-encode" %}
{% set version = "1.1.1" %}
{% set sha256 = "4bb9ce4e7016c0138cf9c2375508595286efa1c8dc15b45baa4c47281c08243b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MI/MITHUN/URI-Encode-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-module-build
    - perl-uri
  run:
    - perl

test:
  imports:
    - URI::Encode

about:
  home: https://github.com/mithun/perl-uri-encode
  summary: 'Simple percent Encoding/Decoding'
  description: |
    This modules provides simple URI (Percent) encoding/decoding. The main purpose of this module (at least for me) was to provide an easy method to encode strings (mainly URLs) into a format which can be pasted into a plain text emails, and that those links are 'click-able' by the person reading that email. This can be accomplished by NOT encoding the reserved characters.
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  dev_url: https://github.com/mithun/perl-uri-encode

extra:
  recipe-maintainers:
    - fgiacomoni
    - conda-forge/perl-packagers
